version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: topic-classifier-api
    depends_on:
      ollama:
        condition: service_healthy
    env_file:
      - .env
    environment:
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://ollama:11434}
      MODEL_NAME: ${MODEL_NAME:-gemma:2b}
      LLM_TEMPERATURE: ${LLM_TEMPERATURE:-0.1}
      LLM_NUM_PREDICT: ${LLM_NUM_PREDICT:-400}
      LLM_TIMEOUT_SECS: ${LLM_TIMEOUT_SECS:-60}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

volumes:
  ollama_models:
